# Generated by Django 5.0.2 on 2024-02-08 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('count', models.IntegerField()),
                ('des', models.TextField(max_length=512)),
                ('photo', models.ImageField(upload_to='media')),
                ('price', models.FloatField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_web.category')),
            ],
        ),
    ]
