# Generated by Django 5.0.2 on 2024-02-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_web', '0002_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
